### ISSUE TITLE
TTFs

### ISSUE THREAD

**Issue by davelab6** [hyper-type/hahmlet#1]
GF needs TTFs built via fontmake based build script :)

**Comment by Mark2Mark** [comment]
@davelab6 We tried fontMake and came so far that it creates 3 master UFOs and a design space file.
However fontMake stopped with an Error

One of them is:
`The copyright was normalized for storage in the CFF table and consequently some characters were dropped: 'Copyright 2020 The Hahmlet Project Authors https:github.comhyper-typehahmlet'`
> Why does it remove the slash from the URL, it’s crippled now.

The rest of the Error is:
```
Traceback (most recent call last):
  File "/usr/local/bin/fontmake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fontmake/__main__.py", line 425, in main
    project.run_from_glyphs(glyphs_path, **args)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 672, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 889, in run_from_designspace
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 952, in _run_from_designspace_static
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 1013, in run_from_ufos
    self.build_otfs(ufos, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 204, in build_otfs
    self.save_otfs(ufos, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 367, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 480, in save_otfs
    for font, ufo in zip(fonts, ufos):
  File "/usr/local/lib/python3.7/site-packages/fontmake/font_project.py", line 345, in _iter_compile
    yield compile_func(ufo, debugFeatureFile=debugFeatureFile, **options)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 134, in compileOTF
    debugFeatureFile=debugFeatureFile,
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/__init__.py", line 521, in compileFeatures
    otFont = featureCompiler.compile()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 120, in compile
    self.setupFeatures()
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 215, in setupFeatures
    featureFile = parseLayoutFeatures(self.ufo)
  File "/usr/local/lib/python3.7/site-packages/ufo2ft/featureCompiler.py", line 43, in parseLayoutFeatures
    doc = parser.parse()
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 61, in parse
    statements.append(self.parse_glyphclass_definition_())
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 221, in parse_glyphclass_definition_
    glyphs = self.parse_glyphclass_(accept_glyphname=False)
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/parser.py", line 325, in parse_glyphclass_
    self.cur_token_location_)
```

**Comment by Mark2Mark** [comment]
@davelab6 bump!

**Comment by davelab6** [comment]
We don't want cff, so I'm not familiar with this. Is there slash allowed according to the cff table spec?

**Comment by Mark2Mark** [comment]
I didn’t ask it to do CFF either, FontMake was throwing that at me what you can see above. I just followed the FontMake instructions.

**Comment by Mark2Mark** [comment]
According to [fontMake docs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html)
"The OpenType spec requires ASCII for the POSTSCRIPT_NAME (nameID 6).

For COPYRIGHT_NOTICE (nameID 0) ASCII is required because that string should be the same in CFF fonts which also have this requirement in the OpenType spec.

Note: A common place where we find non-ASCII strings is on name table entries with NameID > 18, which are expressly for localising the ASCII-only IDs into Hindi / Arabic / etc."

**Comment by aaronbell** [comment]
Is this still an open issue?

**Comment by aaronbell** [comment]
The branch / PR I recently submitted builds TTFs without any issues.
